### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by jamiehadd** [jdmoorman/cookiecutter-academic-pypackage#5]
## Description
When using the command "pip install cookiecutter", the terminal returned the error "Could not find a version that satisfies the requirement cookiecutter (from versions: ). No matching distribution found for cookiecutter."  

## Expected Behavior
Expected installation to happen.

## Reproduction
pip install cookiecutter

## Environment
...

**Comment by jdmoorman** [comment]
Resolved over email, this was an issue with your `pip`/`python` installation
